apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web_app
  namespace: myargocd
spec:
  project: default
  source:
    repoURL: https://github.com/JulienFuix/minikube_test_web
    targetRevision: HEAD
    path: config_argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: web