apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicwebapp
  namespace: default
  labels:
    app: basicwebapp
spec:
  replicas: 16
  selector:
    matchLabels:
      app: basicwebapp
  template:
    metadata:
      labels:
        app: basicwebapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: basicwebapp
          image: basicwebapp:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000