apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-monitor
  labels:
    app: basicwebapp
spec:
  selector:
    matchLabels:
      app: basicwebapp
  endpoints:
  - port: web
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
