apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.example.com
spec:
  group: example.com
  names:
    plural: webapps
    singular: webapp
    kind: WebApp
    shortNames:
    - wa
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  default: "basicwebapp:latest"  # Default value
                port:
                  type: integer
                  default: 8080  # Default value
