apiVersion: v1
kind: Service
metadata:
  name: basicwebapp-service
  namespace: default
  labels:
    app: basicwebapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: basicwebapp